.. image:: https://github.com/deanishe/alfred-workflow/workflows/build/badge.svg
   :target: https://github.com/deanishe/alfred-workflow/actions?query=workflow%3Abuild
.. image:: https://coveralls.io/repos/github/deanishe/alfred-workflow/badge.svg?branch=master
   :target: https://coveralls.io/github/deanishe/alfred-workflow
.. image:: https://img.shields.io/pypi/status/Alfred-Workflow.svg?style=flat
   :target: https://pypi.python.org/pypi/Alfred-Workflow/
.. image:: https://img.shields.io/pypi/v/Alfred-Workflow.svg?style=flat
   :target: https://pypi.python.org/pypi/Alfred-Workflow/
.. image:: https://img.shields.io/pypi/pyversions/Alfred-Workflow.svg?style=flat
   :target: https://pypi.python.org/pypi/Alfred-Workflow/
