#!/bin/bash

rootdir="$( cd "$( dirname "$0" )/../"; pwd )"


usage() {
  cat > /dev/stderr <<EOS
testone <package.name> <tests/test_script.py>...

Run test script(s) with coverage for one package.

Usage:
    testone <package.name> <test_script.py>...
    testone -h|--help

Options:
    -h, --help  Show this message and exit.

Example:
    extras/testone workflow.notify tests/test_notify.py

EOS
}

log() {
    echo "$@" > /dev/stderr
}


if [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
	usage
  exit 0
fi

if [[ "$1" = "" ]] || [[ "$2" = "" ]]; then
  log "ERROR: Missing argument(s)."
  log ""
  usage
  exit 1
fi

package="$1"
shift

# export PYTEST_ADDOPTS="--cov-report=term"

py.test --cov="${package}" "$@"
# ret1=$?
ret1=${PIPESTATUS[0]}

echo

case "$ret1" in
  0) log "TESTS OK";;
  *) log "TESTS FAILED";;
esac

log ""

# Test coverage
coverage report --fail-under 100 --show-missing
ret2=${PIPESTATUS[0]}

echo

case "$ret2" in
    0) log "COVERAGE OK" ;;
    *) log "COVERAGE FAILED" ;;
esac

if [[ "$ret1" -ne 0 ]]; then
  exit $ret1
fi

exit $ret2
